/**
 * Stable, machine-readable error codes. The frontend switches on `code`,
 * never on `message` (API-CONTRACT.md). Keep these in sync with the contract.
 */
export const ApiCode = {
  // Generic
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  FORBIDDEN: 'FORBIDDEN',
  NOT_FOUND: 'NOT_FOUND',
  CONFLICT: 'CONFLICT',
  INTERNAL: 'INTERNAL',

  // Auth
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  ACCOUNT_LOCKED: 'ACCOUNT_LOCKED',
  ACCOUNT_INACTIVE: 'ACCOUNT_INACTIVE',
  INVALID_CURRENT_PASSWORD: 'INVALID_CURRENT_PASSWORD',

  // Buildings / rooms
  BUILDING_HAS_ROOMS: 'BUILDING_HAS_ROOMS',
  BUILDING_HAS_UTILITY_HISTORY: 'BUILDING_HAS_UTILITY_HISTORY',
  ROOM_HAS_CONTRACTS: 'ROOM_HAS_CONTRACTS',

  // Contracts
  CONTRACT_OVERLAP: 'CONTRACT_OVERLAP',
  ROOM_INACTIVE: 'ROOM_INACTIVE',
  INVALID_DATE_RANGE: 'INVALID_DATE_RANGE',
  TENANT_INACTIVE: 'TENANT_INACTIVE',
  INVALID_CONTRACT_STATE: 'INVALID_CONTRACT_STATE',

  // Invoices / payments
  INVOICE_ALREADY_EXISTS: 'INVOICE_ALREADY_EXISTS',
  INVOICE_VOIDED: 'INVOICE_VOIDED',
  OVERPAYMENT: 'OVERPAYMENT',
  DUPLICATE_OR_NUMBER: 'DUPLICATE_OR_NUMBER',

  // Settings
  UNKNOWN_SETTING: 'UNKNOWN_SETTING',
} as const;

export type ApiCodeValue = (typeof ApiCode)[keyof typeof ApiCode];
